import BaseRepository from '../base/BaseRepository'

import OficialModel from '../models/OficialModel'

export default class OficialRepository extends BaseRepository {
  constructor() {
    super(OficialModel)
  }
}

/*
CaracteristicasLocalModel
FormaSinalizacaoModel
IluminacaoLocalModel
StatusSemaforoModel
TempoLocalModel
TipoAcidenteModel
TipoPistaModel

CaracteristicasLocalRepository
FormaSinalizacaoRepository
IluminacaoLocalRepository
StatusSemaforoRepository
TempoLocalRepository
TipoAcidenteRepository
TipoPistaRepository

CaracteristicasLocalRepository
FormaSinalizacaoRepository
IluminacaoLocalRepository
StatusSemaforoRepository
TempoLocalRepository
TipoAcidenteRepository
TipoPistaRepository

CaracteristicasLocalService
FormaSinalizacaoService
IluminacaoLocalService
StatusSemaforoService
TempoLocalService
TipoAcidenteService
TipoPistaService

CaracteristicasLocalController
FormaSinalizacaoController
IluminacaoLocalController
StatusSemaforoController
TempoLocalController
TipoAcidenteController
TipoPistaController

CaracteristicasLocalRoutes
FormaSinalizacaoRoutes
IluminacaoLocalRoutes
StatusSemaforoRoutes
TempoLocalRoutes
TipoAcidenteRoutes
TipoPistaRoutes

caracteristicasLocalRoutes,
formaSinalizacaoRoutes,
iluminacaoLocalRoutes,
statusSemaforoRoutes,
tempoLocalRoutes,
tipoAcidenteRoutes,
tipoPistaRoutes,
 */
